### ISSUE TITLE
Catch misalignment of delimitation

### ISSUE THREAD

**Issue by sunmuffin42** [doclingjs/parse-leipzig#4]
If there are too many separators (-,=,<,>,etc) in the form compared to gloss submitted, catch the except and throw it, suggesting to the user that their segmentation is potentially off (honestly a pretty good thing for linguists to have haha)

**Comment by amundo** [comment]
Indeed, this is a great idea. 

Do you want to try adding it to `parse-leipzig.js`? Also happy to do it myself.

**Comment by sunmuffin42** [comment]
I'm down. Will need to branch, pull request, etc. So gimme a bit to figure that out.
